name: Build and Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up environment variables
        run: |
          echo "export JWT_SECRET=${{env.JWT_SECRET}}" >> $GITHUB_ENV
          echo "export POSTGRES_HOST=${{env.POSTGRES_HOST}}" >> $GITHUB_ENV
          echo "export POSTGRES_USER=${{env.POSTGRES_USER}}" >> $GITHUB_ENV
          echo "export POSTGRES_PASSWORD=${{env.POSTGRES_PASSWORD}}" >> $GITHUB_ENV
          echo "export POSTGRES_DB=${{env.POSTGRES_DB}}" >> $GITHUB_ENV
          echo "export SUPABASE_KEY=${{env.SUPABASE_KEY}}" >> $GITHUB_ENV
          echo "export SUPABASE_URL=${{env.SUPABASE_URL}}" >> $GITHUB_ENV

      - name: Print Java version
        run: java -version

      - name: Log in to Docker Hub
        run: echo "${{env.DOCKER_HUB_PASSWORD}}" | docker login -u "${{env.DOCKER_HUB_USERNAME}}" --password-stdin

      - name: Build and Deploy
        run: |
          chmod +x build_and_docker.sh
          ./build_and_docker.sh
